title: Aditi Dewangan
logo: /assets/img/profile.jpg
description: aditidew[at]uw[dot]edu
links: [Resume](./assets/Aditi_Dewangan_Resume.pdf) · [GitHub](https://github.com/aditi-dewangan) · [LinkedIn](https://linkedin.com/in/aditi-s-dewangan)
theme: jekyll-theme-minimal
